# Generated by Django 5.1.3 on 2025-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='角色权限字符串'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='角色名称'),
        ),
    ]
