# Generated by Django 5.1.3 on 2025-02-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_sysrole_code_alter_sysrole_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='update_time',
            field=models.DateField(null=True, verbose_name='更新时间'),
        ),
    ]
